// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var getInputJSLine = (function() {
        const readlineSync = require('readline-sync');
        const rl = readlineSync;
        var ans = rl.question('Test readline-sync by typing something and hitting enter ');
        return ans;
    });

function test(param) {
  var input = Curry._1(getInputJSLine, undefined);
  console.log(input);
  
}

test(undefined);

exports.getInputJSLine = getInputJSLine;
exports.test = test;
/*  Not a pure module */
